anifilms/urls.py
from django.contrib import admin
from django.urls import path , re_path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from user import views as user_views
from user.forms import LoginForm
from django.contrib.auth import views as auth_views
from anim import views
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('ControlPanel/', include('control_panel.urls')),
    path('accounts/',include('user.urls')),
    path('',include('anim.urls')),
    path('api/', include('api.urls'), name='api'),
    path('comment/', include('comment.urls')),
    path('rating/', include('rating.urls')),
    path('rosetta/', include('rosetta.urls')),
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/urls.py
from . import views
from django.urls import path

app_name = 'api'

urlpatterns = [
    path('anime/', views.AnimeListView.as_view(), name='anime-list'),
]

comment/urls.py
from django.urls import path
from comment import views

app_name = 'comment'
urlpatterns = [
    path('detail/', views.CommentDetail.as_view(), name='detail'),
    path('list/', views.CommentList.as_view(), name='list'),
    path('create/', views.CommentCreate.as_view(), name='create'),
    path('update/', views.CommentUpdate.as_view(), name='update'),
    path('delete/<str:urlhash>/', views.CommentDelete.as_view(), name='delete'),
    path('react/', views.CommentReact.as_view(), name='react'),
]

rating/urls.py
from django.urls import path

from rating import views

app_name = 'rating'
urlpatterns = [
    path('create/', views.UserRatingCreate.as_view(), name='create'),
    path('info/<str:urlhash>/', views.RatingInfo.as_view(), name='info'),
]

comment/models.py
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.html import format_html

from comment.managers import CommentQuerySet, ReactionQuerySet

User = get_user_model()


class CommentSettings(models.Model):
    name = models.CharField(max_length=30)
    slug = models.SlugField(primary_key=True, help_text='This value will be used in render_comments tag')

    default_profile_image = models.ImageField(upload_to='comment_default_profile_images', null=True, blank=True)
    content_words_count = models.PositiveSmallIntegerField(default=40, help_text='More than this value will have Read More button in comment content')
    status_check = models.BooleanField(default=False, help_text='If True, comment status will be set as d(Delivered) otherwise it will be set as a(Accepted).')
    status_edited_check = models.BooleanField(default=False, help_text='If True, comment status_edited will be set as d(Delivered) otherwise it will be set as a(Accepted) when a comment is edited.')
    allow_spoiler = models.BooleanField(default=True)
    allow_reply = models.BooleanField(default=True)
    allow_edit = models.BooleanField(default=True)
    allow_delete = models.BooleanField(default=True)
    allow_reaction = models.BooleanField(default=True, help_text='First, create a react emoji in React models')
    reaction_type = models.CharField(max_length=6, choices=(('emoji', 'Emoji'), ('source', 'Source')), default='emoji', help_text='Add source in React model')
    per_page = models.PositiveSmallIntegerField(default=10, help_text='Set 0 if you don\'t want pagination (All comments will be shown at once)')
    time_type = models.PositiveSmallIntegerField(default=1, choices=((1, 'Compound'), (2, 'From Now'), (3, 'Date & Time')), help_text='Comment posted time style')
    time_days = models.PositiveSmallIntegerField(default=3, help_text='Less than this value will use FROM NOW type , more will use DATE & TIME type')
    theme_direction = models.CharField(max_length=3, choices=(('ltr', 'LTR (Left to Right)'), ('rtl', 'RTL (Right to Left)')), default='ltr')
    theme_dark_mode = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Comment Settings'
        verbose_name_plural = 'Comment Settings'

    def __str__(self):
        return f'{self.name} - [{self.slug}]'


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    content_main = models.TextField()
    content = models.TextField()  # edited content will store here
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='children', null=True, blank=True)
    is_spoiler = models.BooleanField(default=False)
    is_pinned = models.BooleanField(default=False)
    STATUS_CHOICES = (('d', 'Delivered'), ('a', 'Accepted'), ('r', 'Rejected'))
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='d')
    STATUS_EDITED_CHOICES = (('n', 'None'), ('d', 'Delivered'), ('a', 'Accepted'), ('r', 'Rejected'))
    status_edited = models.CharField(max_length=1, choices=STATUS_EDITED_CHOICES, default='n')
    urlhash = models.CharField(max_length=50, unique=True, editable=False)
    posted = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    objects = CommentQuerySet.as_manager()

    class Meta:
        ordering = ('-is_pinned', '-posted')

    def __str__(self):
        if not self.parent:
            return f'{self.content_main[:20]}'
        else:
            return f'[RE] ({self.parent.content_main[:10]}) : {self.content_main[:15]}'

    def set_unique_urlhash(self):
        if not self.urlhash:
            self.urlhash = self.__class__.objects.generate_urlhash()
            while self.__class__.objects.filter(urlhash=self.urlhash).exists():
                self.urlhash = self.__class__.objects.generate_urlhash()

    def save(self, *args, **kwargs):
        self.set_unique_urlhash()
        super(Comment, self).save(*args, **kwargs)

    def is_updated(self):
        return True if self.updated.timestamp() > self.posted.timestamp() and self.status_edited == 'a' else False

    is_updated.boolean = True

    @property
    def is_parent(self):
        return self.parent is None


class React(models.Model):
    slug = models.CharField(max_length=20, unique=True)
    emoji = models.CharField(max_length=5)
    source = models.ImageField(upload_to='react_source', null=True, blank=True)

    def __str__(self):
        return self.slug

    def source_file(self):
        return format_html(f"<img style='height:20px' src='{self.source.url}' alt='{self.emoji}'>") if self.source else 'X'


class Reaction(models.Model):
    user = models.ForeignKey(User, related_name='comment_reactions', on_delete=models.CASCADE, editable=False)
    comment = models.ForeignKey(Comment, related_name='reactions', on_delete=models.CASCADE, editable=False)
    react = models.ForeignKey(React, related_name='reactions', on_delete=models.CASCADE, editable=False)

    objects = ReactionQuerySet.as_manager()

    class Meta:
        unique_together = ['user', 'comment']

    def __str__(self):
        return f'{self.user} <{self.react.slug}> ({self.comment.content_main[:20]})'

comment/forms.py
from django import forms
from comment.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', 'is_spoiler')

comment/views.py
import json

from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse, HttpResponse, HttpResponseBadRequest
from django.shortcuts import render
from django.utils import timezone
from django.views import View
from django.views.generic import ListView, TemplateView

from comment.forms import CommentForm
from comment.mixins import CommentMixin
from comment.models import Comment, Reaction, React, CommentSettings


class CommentDetail(TemplateView):
    template_name = 'comment/comment/comment_body.html'

    def get(self, request, *args, **kwargs):
        urlhash = request.GET.get('urlhash')
        settings_slug = request.GET.get('settings_slug')
        context = {
            'comment': Comment.objects.get(urlhash=urlhash),
            'settings': CommentSettings.objects.get(slug=settings_slug)
        }
        return render(request, self.template_name, context=context)


class CommentList(ListView):
    context_object_name = 'comments'
    template_name = 'comment/comment/comment_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        settings_slug = self.request.GET.get('settings_slug')
        context['settings'] = CommentSettings.objects.get(slug=settings_slug)
        return context

    def get_queryset(self):
        queryset = None
        if self.request.GET:
            app_name = self.request.GET.get('app_name')
            model_name = self.request.GET.get('model_name')
            object_id = self.request.GET.get('object_id')
            settings_slug = self.request.GET.get('settings_slug')
            comment_settings = CommentSettings.objects.get(slug=settings_slug)
            content_type = ContentType.objects.get(app_label=app_name, model=model_name.lower())
            queryset = Comment.objects.filter(content_type=content_type, object_id=object_id)
            queryset = queryset.filter_accepted().filter_parents()
            queryset = queryset.order_pinned_newest()

            # Pagination
            page = self.request.GET.get('page', 1)
            if comment_settings.per_page == 0:
                paginator = Paginator(queryset, queryset.count())
            else:
                paginator = Paginator(queryset, comment_settings.per_page)
            try:
                queryset = paginator.page(page)
            except PageNotAnInteger:
                queryset = paginator.page(1)
            except EmptyPage:
                queryset = paginator.page(paginator.num_pages)

        return queryset


class CommentCreate(CommentMixin, View):
    def post(self, request, *args, **kwargs):
        data = json.loads(request.body)
        form = CommentForm(data=data)
        if form.is_valid():
            comment = form.save(commit=False)

            comment.user = request.user
            comment.content_main = comment.content
            app_name = data.get('app_name', None)
            model_name = data.get('model_name', None)
            object_id = data.get('object_id', None)
            parent_id = data.get('parent_id', None)
            settings_slug = data.get('settings_slug', None)
            comment_settings = CommentSettings.objects.get(slug=settings_slug)
            time_posted = timezone.now()
            comment.content_type = ContentType.objects.get(app_label=app_name, model=model_name.lower())
            comment.object_id = object_id

            if parent_id:
                parent_comment = Comment.objects.get(urlhash=parent_id)
                comment.parent = parent_comment
            else:
                comment.parent = None
            comment.posted = time_posted

            if not comment_settings.status_check:
                comment.status = 'a'

            comment.save()
            return HttpResponse(status=200)
        else:
            return HttpResponseBadRequest()


class CommentUpdate(CommentMixin, View):
    def post(self, request, *args, **kwargs):
        data = json.loads(request.body)
        form = CommentForm(data=data)
        if form.is_valid():
            comment = Comment.objects.get(urlhash=data.get('urlhash'))
            new_content = data.get('content')
            new_is_spoiler = data.get('is_spoiler')
            if comment.content_main != new_content or comment.is_spoiler != new_is_spoiler:
                comment.content = new_content
                comment.is_spoiler = new_is_spoiler

                settings_slug = data.get('settings_slug', None)
                comment_settings = CommentSettings.objects.get(slug=settings_slug)

                if comment_settings.status_edited_check and comment.content_main != comment.content:
                    comment.status_edited = 'd'
                    comment.save()
                else:
                    comment.status_edited = 'a'
                    comment.content_main = comment.content
                    comment.save()

                return JsonResponse({'urlhash': comment.urlhash}, status=200)
            return HttpResponse(status=200)
        else:
            return HttpResponseBadRequest()


class CommentDelete(CommentMixin, View):
    def get(self, request, urlhash, *args, **kwargs):
        return render(request, 'comment/forms/comment_form_delete.html', context={'urlhash': urlhash})

    def post(self, request, urlhash, *args, **kwargs):
        comment = Comment.objects.get(urlhash=urlhash)
        if comment:
            comment.delete()
            return HttpResponse(status=200)
        return HttpResponseBadRequest()


class CommentReact(CommentMixin, View):
    def get(self, request, *args, **kwargs):
        urlhash = request.GET.get('urlhash')
        context = {'comment': Comment.objects.get(urlhash=urlhash)}
        return render(request, 'comment/comment/comment_reactions.html', context=context)

    def post(self, request, *args, **kwargs):
        user = request.user
        data = json.loads(request.body)
        comment_urlhash = data.get('urlhash', None)
        react_slug = data.get('react_slug', None)

        reaction = Reaction.objects.filter(user=user, comment__urlhash=comment_urlhash).first()

        if reaction:  # Update Previous Reaction
            if reaction.react.slug == react_slug:  # Delete Previous Reaction
                reaction.delete()
            else:  # Change Previous Reaction
                react = React.objects.get(slug=react_slug)
                reaction.react = react
                reaction.save()
        else:  # Create New Reaction
            comment = Comment.objects.get(urlhash=comment_urlhash)
            react = React.objects.get(slug=react_slug)
            Reaction.objects.create(user=user, comment=comment, react=react)

        return HttpResponse(status=200)

comment/templates/comment/forms/comment_form_create.html
{% load i18n %}
{% load comment_tags %}

<form id="form-comment-create" method="post" action="{% url 'comment:create' %}">{% csrf_token %}

    {# render info inputs #}
    {% include 'comment/comment/object_info.html' with object_info=object_info settings=settings %}

    {# main form #}
    <div class="block rounded-lg bg-textarea-bg-light dark:bg-textarea-bg-dark p-4">
        {% if request.user.is_authenticated %}
            <textarea name="content" id="id_content" rows="5" placeholder="{% trans 'Write Something...' %}" spellcheck="false" class="mb-4 box-border block min-h-[124px] w-full resize-y bg-transparent px-2 text-base outline-0 text-textarea-text-light dark:text-textarea-text-dark selection:bg-textarea-text-selection-light dark:selection:bg-text-selection-dark placeholder:text-textarea-text-placeholder-light dark:placeholder:text-textarea-text-placeholder-dark {% if LANGUAGE_CODE == 'fa-ir' %}font-default-fd{% else %}font-default{% endif %}"></textarea>

            <div class="flex justify-end">
                {#ALLOW_SPOILER#}
                {% if settings.allow_spoiler %}
                    <label class="ltr:mr-4 rtl:ml-4 grid content-center">
                        <input type="checkbox" name="is_spoiler" id="id_is_spoiler" class="peer sr-only"/>
                        {#ICON EYE#}
                        <span class="block cursor-pointer peer-checked:hidden">{% include 'comment/icons/icon_eye.html' with class='inline-block w-8 fill-none stroke-icon-spoiler-light dark:stroke-icon-spoiler-dark' %}</span>
                        {#ICON EYE OFF#}
                        <span class="hidden cursor-pointer peer-checked:block">{% include 'comment/icons/icon_eye_off.html' with class='inline-block w-8 fill-icon-spoiler-light dark:fill-icon-spoiler-dark' %}</span>
                    </label>
                {% endif %}
                <button type="button" onclick="CreateComment('form-comment-create','{{ settings.status_check }}')" class="rounded-lg border-none bg-btn-send-bg-light dark:bg-btn-send-bg-dark py-2 px-6 text-xl text-btn-send-text-light dark:text-btn-send-text-dark dark:font-semibold outline-0 shadow-md">{% trans 'Send' context 'form-button' %}</button>
            </div>
        {% else %}
            <div><a href="{% get_settings 'LOGIN_URL' %}" class="font-bold text-btn-login-text-light dark:text-btn-login-text-dark">{% trans 'Login to comment' context 'login-required' %}</a></div>
        {% endif %}
    </div>

</form>

comment/templates/comment/forms/comment_form_delete.html
{% load i18n %}
<div class="relative z-10" aria-labelledby="modal-title" role="dialog" aria-modal="true">

    <div class="fixed inset-0 bg-gray-500 bg-opacity-70 transition-opacity"></div>

    <div class="fixed inset-0 z-10 overflow-y-auto">
        <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
            <div class="relative transform overflow-hidden rounded-lg bg-delete-from-bg-light dark:bg-delete-from-bg-dark ltr:text-left rtl:text-right shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg">
                <div class="bg-delete-from-bg-light dark:bg-delete-from-bg-dark px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
                    <div class="sm:flex sm:items-start">
                        <div class="mt-3 text-center sm:mt-0 sm:ltr:ml-4 sm:rtl:mr-4 ltr:sm:text-left rtl:sm:text-right">
                            <h3 class="text-lg font-medium leading-6 text-delete-from-text-light dark:text-delete-from-text-dark" id="modal-title">{% trans 'Delete Comment' %}</h3>
                            <div class="mt-2">
                                <p class="text-sm text-delete-from-subtext-light dark:text-delete-from-subtext-dark">
                                    {% blocktrans %}Are you sure you want to delete your comment? All of your replies will be permanently removed. This action can not be undone.{% endblocktrans %}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <form id="form-comment-delete-{{ urlhash }}" method="post" action="{% url 'comment:delete' urlhash %}" class="px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6">{% csrf_token %}
                    <button type="button" onclick="DeleteComment('{{ urlhash }}')" class="inline-flex w-full justify-center rounded-md border border-transparent bg-btn-delete-bg-light dark:bg-btn-delete-bg-dark text-btn-delete-text-light dark:text-btn-delete-text-dark px-4 py-2 text-base font-medium shadow-sm sm:ltr:ml-3 sm:rtl:mr-3 sm:w-auto sm:text-sm">{% trans 'Delete' context 'form-button' %}</button>
                    <button type="button" onclick="ResetDeleteCommentForm()" class="mt-3 inline-flex w-full justify-center rounded-md border border-gray-300 bg-btn-cancel-bg-light dark:bg-btn-cancel-bg-dark text-btn-cancel-text-light dark:text-btn-cancel-text-dark px-4 py-2 text-base font-medium shadow-sm sm:mt-0 sm:ltr:ml-3 sm:rtl:mr-3 sm:w-auto sm:text-sm">{% trans 'Cancel' context 'form-button' %}</button>
                </form>
            </div>
        </div>
    </div>

</div>

comment/templates/comment/forms/comment_form_edit.html
{% load i18n %}

<form id="form-comment-edit-{{ comment.urlhash }}" method="post" action="{% url 'comment:update' %}">{% csrf_token %}
    <div class="block rounded-lg bg-textarea-bg-light dark:bg-textarea-bg-dark pb-4 pt-1 ltr:pr-4 rtl:pl-4 ltr:pl-1 rtl:pr-1">
        <textarea name="content" oninput="CheckEditTextarea('form-comment-edit-{{ comment.urlhash }}')" spellcheck="false" class="p-1 rounded-md block w-full border-2 resize-y bg-transparent box-border text-base mb-2 outline-0 min-h-[66px] text-textarea-text-light dark:text-textarea-text-dark border-textarea-bg-light dark:border-textarea-bg-dark selection:bg-textarea-text-selection-light dark:selection:bg-text-selection-dark placeholder:text-textarea-text-placeholder-light dark:placeholder:text-textarea-text-placeholder-dark {% if LANGUAGE_CODE == 'fa-ir' %}font-default-fd{% else %}font-default{% endif %}">{{ comment.content_main }}</textarea>

        <div class="flex justify-end">
            {#ALLOW_SPOILER#}
            {% if settings.allow_spoiler %}
                <label class="ltr:mr-4 rtl:ml-4 grid content-center">
                    <input type="checkbox" name="is_spoiler" id="id_is_spoiler" class="peer sr-only" {% if comment.is_spoiler %}checked="checked"{% endif %}/>
                    {#ICON EYE#}
                    <span class="block cursor-pointer peer-checked:hidden">{% include 'comment/icons/icon_eye.html' with class='inline-block w-8 fill-none stroke-icon-spoiler-light dark:stroke-icon-spoiler-dark' %}</span>
                    {#ICON EYE OFF#}
                    <span class="hidden cursor-pointer peer-checked:block">{% include 'comment/icons/icon_eye_off.html' with class='inline-block w-8 fill-icon-spoiler-light dark:fill-icon-spoiler-dark' %}</span>
                </label>
            {% endif %}
            <label for="toggle-edit-{{ comment.urlhash }}" onclick="ResetEditCommentForm('form-comment-edit-{{ comment.urlhash }}','{{ comment.content_main }}','{{ comment.is_spoiler }}')" class="inline cursor-pointer rounded-lg border-none bg-btn-cancel-bg-light dark:bg-btn-cancel-bg-dark py-2 px-6 text-xl text-btn-cancel-text-light dark:text-btn-cancel-text-dark outline-0 shadow-md ltr:mr-2 rtl:ml-2">{% trans 'Cancel' context 'form-button' %}</label>
            <button type="button" onclick="EditComment('form-comment-edit-{{ comment.urlhash }}','{{ settings.slug }}','{{ settings.status_edited_check }}')" class="rounded-lg border-none bg-btn-edit-bg-light dark:bg-btn-edit-bg-dark py-2 px-6 text-xl text-btn-edit-text-light dark:text-btn-edit-text-dark outline-0 shadow-md">{% trans 'Edit' context 'form-button' %}</button>
        </div>
    </div>
</form>

comment/templates/comment/forms/comment_form_reply.html
{% load i18n %}
{% load comment_tags %}

<form id="form-comment-reply-{{ comment.urlhash }}" method="post" action="{% url 'comment:create' %}">{% csrf_token %}

    {# render info inputs #}
    {% include 'comment/comment/object_info.html' with object_info=object_info %}

    {# parent_id #}
    <input type="hidden" name="parent_id" value="{{ comment.urlhash }}" hidden>
    <input type="hidden" name="page" value="{{ page }}" hidden>

    {# main form #}
    <div class="block rounded-lg bg-textarea-bg-light dark:bg-textarea-bg-dark p-4">
        {% if request.user.is_authenticated %}
            <textarea name="content" id="id_content" rows="2" placeholder="{% trans 'Reply to' %} {{ comment.user.username }}" spellcheck="false" class="mb-4 box-border block min-h-[56px] w-full resize-y bg-transparent px-2 text-base outline-0 text-textarea-text-light dark:text-textarea-text-dark selection:bg-textarea-text-selection-light dark:selection:bg-text-selection-dark placeholder:text-textarea-text-placeholder-light dark:placeholder:text-textarea-text-placeholder-dark {% if LANGUAGE_CODE == 'fa-ir' %}font-default-fd{% else %}font-default{% endif %}"></textarea>

            <div class="flex justify-end">
                {# ALLOW_SPOILER#}
                {% if settings.allow_spoiler %}
                    <label class="ltr:mr-4 rtl:ml-4 grid content-center">
                        <input type="checkbox" name="is_spoiler" id="id_is_spoiler" class="peer sr-only"/>
                        {#ICON EYE#}
                        <span class="block cursor-pointer peer-checked:hidden">{% include 'comment/icons/icon_eye.html' with class='inline-block w-8 fill-none stroke-icon-spoiler-light dark:stroke-icon-spoiler-dark' %}</span>
                        {#ICON EYE OFF#}
                        <span class="hidden cursor-pointer peer-checked:block">{% include 'comment/icons/icon_eye_off.html' with class='inline-block w-8 fill-icon-spoiler-light dark:fill-icon-spoiler-dark' %}</span>
                    </label>
                {% endif %}
                <button type="button" onclick="CreateComment('form-comment-reply-{{ comment.urlhash }}','{{ settings.status_check }}')" class="rounded-lg border-none py-2 px-6 text-xl outline-0 shadow-md bg-btn-reply-bg-light dark:bg-btn-reply-bg-dark text-btn-reply-text-light dark:text-btn-reply-text-dark">{% trans 'Reply' context 'form-button' %}</button>
            </div>
        {% else %}
            <div><a href="{% get_settings 'LOGIN_URL' %}" class="font-bold text-btn-login-text-light dark:text-btn-login-text-dark">{% trans 'Login to reply' context 'login-required' %}</a></div>
        {% endif %}
    </div>

</form>