anim/urls.py
from django.urls import path, re_path, include
from . import views
from user import views as user_views

app_name = 'anime'


urlpatterns = [
    path('',views.list, name='list'),
    path('video/<int:video_id>',views.view_video, name='video'),
    path('<str:anim_name>',views.view, name='view'),
    path('tag/<str:slug>/', views.tagged, name="tagged"),
    path('save/<int:pk>',views.SaveView, name='anim_save'),
]

api/urls.py
from . import views
from django.urls import path

app_name = 'api'

urlpatterns = [
    path('anime/', views.AnimeListView.as_view(), name='anime-list'),
]

comment/urls.py
from django.urls import path
from comment import views

app_name = 'comment'
urlpatterns = [
    path('detail/', views.CommentDetail.as_view(), name='detail'),
    path('list/', views.CommentList.as_view(), name='list'),
    path('create/', views.CommentCreate.as_view(), name='create'),
    path('update/', views.CommentUpdate.as_view(), name='update'),
    path('delete/<str:urlhash>/', views.CommentDelete.as_view(), name='delete'),
    path('react/', views.CommentReact.as_view(), name='react'),
]

control_panel/urls.py
from django.urls import path
from . import views

app_name = 'ControlPanel'

urlpatterns = [
    path('',views.anims,name='home'),
    path('accounts/',views.accounts,name='accounts'),
    path('create/',views.create_anim,name='create'),
    path('edit/<int:anim_id>',views.edit_anim,name='edit'),
    path('add_photo/<int:anim_id>',views.add_photo,name='add_photo'),
    path('change_ep/',views.change_ep, name='change_ep'),
    path('change_active_status/',views.change_active_status, name='change_active_status'),
    path('set_admin/',views.set_admin, name='set_admin'),
    path('<int:anim_id>',views.Upload, name='upload'),
    path('clear/<int:anim_id>', views.clear_database, name='clear_database'),
    path('delete', views.delete, name='delete'),
    path('msg/<str:redirct>/<str:message>',views.view_message,name='msg'),
]

rating/urls.py
from django.urls import path

from rating import views

app_name = 'rating'
urlpatterns = [
    path('create/', views.UserRatingCreate.as_view(), name='create'),
    path('info/<str:urlhash>/', views.RatingInfo.as_view(), name='info'),
]

control_panel/forms.py
from django import forms


class pform(forms.Form):
    file = forms.FileField()

class episodForm(forms.Form):
    episod = forms.IntegerField(required=False,max_value=2000, min_value=1)


    

anim/views.py
from django.shortcuts import render, redirect, HttpResponse,get_list_or_404, get_object_or_404
from .models import anim, anim_video, anim_sub, View
from user.models import Save
from django.conf import settings as s
import boto3
from django.core.paginator import Paginator
from django.db.utils import IntegrityError
import json
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import render
from time import gmtime, strftime
import datetime
import django
from taggit.models import Tag
from functools import reduce
from operator import or_
from django.db.models import Count,Avg,Q
from datetime import datetime, timedelta
from django.utils import translation
from django.contrib.auth.decorators import login_required



LIARA = {
    'endpoint': s.AWS_S3_ENDPOINT_URL,
    'accesskey': s.AWS_ACCESS_KEY_ID,
    'secretkey': s.AWS_SECRET_ACCESS_KEY,
    'bucket': s.AWS_STORAGE_BUCKET_NAME
}


def check_lang(request):
    if request.user.is_authenticated:
        translation.activate(request.user.user.language)
    
def list(request):
    check_lang(request)
    top_anime = anim.objects.annotate(view_count=Count('view')).order_by('-view_count', 'ratings__average').filter(accepted=True).distinct()[:4]
    
    # Calculate the average rating for each anim
    anims = anim.objects.annotate(average_ratings=Avg('ratings__average')).filter(accepted=True)

    paginator = Paginator(get_list_or_404(anims) , 20)

    page_number = request.GET.get('page')
    if page_number is not None and page_number != "":
        page_obj = paginator.get_page(page_number)
    else:
        page_obj = paginator.get_page(1)
    totalpage=  page_obj.paginator.num_pages
    tags = Tag.objects.all()
    context = {
        'anims': page_obj,
        'page_number':page_number,
        'totalpage':totalpage,
        'tags':tags,
        'top_anime': top_anime,
    }

    if request.method == 'GET':
        query = request.GET.get('q')
        genre = request.GET.get('genre')
        rating = request.GET.get('rating')
        lookups = []
        if genre is not None and genre != "":
            lookups.append(Q(tags__slug=genre))
        if rating is not None and rating != "":
            lookups.append(Q(ratings__average__gte=rating))

        if query is not None and query != "":
            lookups.append(Q(name_english__icontains=query) | Q(name_Japanese__icontains=query) | Q(name_farsi__icontains=query) | Q(description__icontains=query))

        if lookups:
            print('lookups')
            anims = anim.objects.filter(reduce(or_, lookups)).distinct()

        context={
            'anims': anims,
            'tags':tags,
            'top_anime': top_anime,
            'page_number':page_number,
            'totalpage':totalpage
        }
    return render(request, 'anim/anims.html',context)


def tagged(request, slug):
    check_lang(request)
    tag = get_object_or_404(Tag, slug=slug)
    common_tags = anim.tags.most_common()
    posts = anim.objects.filter(tags=tag)
    top_anime = anim.objects.annotate(view_count=Count('view')).order_by('-view_count', 'ratings__average').distinct()[:4]
    context = {
        'tag':tag,
        'tags':common_tags,
        'top_anime': top_anime,
        'anims':posts,
    }
    return render(request, 'anim/anims.html', context)

def view(request,anim_name):
    check_lang(request)
    anime = get_object_or_404(anim,name_Japanese=anim_name)
    anim_videos = anim_video.objects.filter(anim=anime)
    anim_subs = anim_sub.objects.filter(anim=anime)
    translators = set([video.added_by for video in anim_videos] + [sub.added_by for sub in anim_subs])
    similar = anime.tags.similar_objects()[:4]
    if not request.session.get(f'viewed-{anime.id}', False):
        View.objects.create(anim=anime)
        request.session[f'viewed-{anime.id}'] = True

    return render(request,'anim/view.html',context={'anim':anime,'similars':similar,'translators':translators})

def view_video(request, video_id):
    check_lang(request)
    video = anim_video.objects.get(id=video_id)
    
    return render(request,'anim/play_anime.html',context={'video':video})


@login_required
def SaveView(request, pk):
    check_lang(request)
    post = get_object_or_404(anim, id=pk)
    save = Save(owner=request.user, anim=post)
    try:
        save.save()  # In case of duplicate key
    except IntegrityError as e:
        pass
    return redirect('accounts:profile',request.user.username)


def get_media(request, media_key):
    s3 = boto3.client('s3',
        endpoint_url=LIARA['endpoint'],
        aws_access_key_id=LIARA['accesskey'],
        aws_secret_access_key=LIARA['secretkey']
    )
    bucket_name = LIARA['bucket']
    file_url = s3.generate_presigned_url(
        'get_object',
        Params={'Bucket': bucket_name, 'Key': 'media/' + media_key},
        ExpiresIn=3600  # 1 hour expiry
    )
    return redirect(file_url)

def delete_file(request, file_code):
    s3 = boto3.client('s3',
        endpoint_url=LIARA['endpoint'],
        aws_access_key_id=LIARA['accesskey'],
        aws_secret_access_key=LIARA['secretkey']
    )
    bucket_name = LIARA['bucket']
    s3.delete_object(Bucket=bucket_name, Key='media/' + file_code)
    return redirect('list_file')




control_panel/views.py
from django.shortcuts import render, get_list_or_404, redirect,get_object_or_404
from django.views import View
from anim.models import anim_video, anim
from .forms import pform, episodForm
from django.conf import settings as s
import boto3
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
import random
from anim.forms import animForm, animForme
from user.models import Profile
from django.contrib import messages
from django.views.decorators.csrf import csrf_protect
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.http import Http404
from django.utils import translation


LIARA = {
    'endpoint': s.AWS_S3_ENDPOINT_URL,
    'accesskey': s.AWS_ACCESS_KEY_ID,
    'secretkey': s.AWS_SECRET_ACCESS_KEY,
    'bucket': s.AWS_STORAGE_BUCKET_NAME
}

def check_lang(request):
    if request.user.is_authenticated:
        translation.activate(request.user.user.language)
    


@login_required
def anims(request):
    check_lang(request)
    if get_object_or_404(Profile,user=request.user).admin == True:
        anims = anim.objects.all()
        return render(request, 'list/anims.html',{'anims':anims})
    else:
        raise Http404

@login_required
def accounts(request):
    check_lang(request)
    if get_object_or_404(Profile,user=request.user).admin == True:
        profiles = Profile.objects.all()
        return render(request, 'list/accounts.html',{'profiles':profiles})
    else:
        raise Http404


@login_required
def create_anim(request):
    check_lang(request)
    if get_object_or_404(Profile,user=request.user).admin == True:
        if request.method == 'GET':
            form = animForme()
            return render(request, 'form/create.html',{'form':form})
        if request.method == 'POST':
            form = animForme(request.POST, request.FILES)
            if form.is_valid():
                if request.user.is_authenticated:
                    anime = anim.objects.create(added_by=request.user, **form.cleaned_data)
                    anime.save()
                    messages.success(request, 'انیمه اضافه شد.')
                    return redirect('ControlPanel:anims')
                else:
                    messages.error(request, 'خطا در افزودن: کاربر احراز هویت نشده است.')
                    return render(request, 'form/create.html',{'form':form})
            else:
                messages.error(request, 'خطا در افزودن')
                return render(request, 'form/create.html',{'form':form})
    else:
        raise Http404


@login_required
def edit_anim(request, anim_id):
    check_lang(request)
    if get_object_or_404(Profile,user=request.user).admin == True:
        anime = get_object_or_404(anim,id=anim_id)
        if request.method == 'GET':
            form = animForme(instance=anime)
            return render(request, 'form/edit.html', {'form':form,'anim':anime})

        if request.method == 'POST':
            form = animForme(request.POST, request.FILES, instance=anime)
            if form.is_valid():
                form.save()
                messages.success(request, 'انیمه ویرایش شد')
                return redirect('ControlPanel:anims')
            else:
                messages.error(request, 'خطا در ویرایش:')
                return render(request, 'form/edit.html',{'form':form,'anim':anime})
    else:
        raise Http404


@login_required
def add_photo(request, anim_id):
    check_lang(request)
    if get_object_or_404(Profile,user=request.user).admin == True:
        anime = get_object_or_404(anim,id=anim_id)
        print('ok1')
        if request.method == 'POST':
            print('ok2')
            form = pform(request.POST, request.FILES)
            if form.is_valid():
                Cloudfile = request.FILES.get('file')
                filename = (anime.name_english +'/' + request.user.username + '/' + str(random.randint(0,99999)) + Cloudfile.name ) 
                s3 = boto3.client('s3',
                    endpoint_url=LIARA['endpoint'],
                    aws_access_key_id=LIARA['accesskey'],
                    aws_secret_access_key=LIARA['secretkey']
                )
                bucket_name = LIARA['bucket']
                anime.photo = Cloudfile
                anime.photo.name = filename
                anime.save()
                return redirect('ControlPanel:anims')
            else:
                return redirect('ControlPanel:anims')
    else:
        raise Http404


@login_required
def view_message(request,redirct,message):
    messages.success(request, message)
    return redirect(redirct)


@login_required
def change_ep(request):
    response_data = {}
    if request.POST.get('action') == 'post' and get_object_or_404(Profile,user=request.user).admin == True:
        video = anim_video.objects.get(id=request.POST.get('id'))
        video.episod = request.POST.get('episod')
        if int(request.POST.get('episod')) <= int(video.anim.max_episod):
            video.save()
            response_data['saved'] = True
            return JsonResponse(response_data)
        else:
            return ValueError
    raise Http404

@login_required
def change_active_status(request):
    response_data = {}
       
    if request.POST.get('action') == 'post' and get_object_or_404(Profile,user=request.user).admin == True and request.user.is_staff:
        anime = anim.objects.get(id=request.POST.get('id'))
        if anime.accepted:
            anime.accepted = False 
            data = {'is_valid': False}
        else:
            anime.accepted = True
            data = {'is_valid': True}
        anime.save()
        
        return JsonResponse(data)
    else:
        raise Http404


@login_required
def set_admin(request):
    response_data = {}
       
    if request.POST.get('action') == 'post' and get_object_or_404(Profile,user=request.user).admin == True and request.user.is_staff:
        user = Profile.objects.get(id=request.POST.get('id'))
        if user.admin:
            user.admin = False 
            data = {'is_valid': False}
        else:
            user.admin = True
            data = {'is_valid': True}
        user.save()
        
        return JsonResponse(data)
    else:
        raise Http404



@login_required
def Upload(request, anim_id):
    check_lang(request)
    if get_object_or_404(Profile,user=request.user).admin == True:
        anime = get_object_or_404(anim,id=anim_id)
        if request.method == 'GET':
            videos_list = anim_video.objects.filter(anim=anime,added_by=request.user).order_by('-episod')
            form = episodForm()
            return render(request, 'upload/upload.html', {'videos': videos_list,'eform':form,'anim':anime})

        if request.method == 'POST':
            form = pform(request.POST, request.FILES)
            if form.is_valid():
                Cloudfile = request.FILES.get('file')
                filename = (anime.name_english +'/' + request.user.username + '/' + str(random.randint(0,99999)) + Cloudfile.name ) 
                videos = anim_video.objects.filter(anim=anime)
                if videos.last():
                    episod = videos.last().episod + 1
                else:
                    episod = 1
                vid_anim = anim_video.objects.create(
                    anim=anime,
                    added_by=request.user,
                    video=filename,
                    episod=episod
                )
                
                vid_anim.video = Cloudfile
                vid_anim.video.name = filename
                vid_anim.save()
                data = {'is_valid': True, 'name': Cloudfile.name, 'url': filename, 'episod':1}
            else:
                data = {'is_valid': False}
        return JsonResponse(data)
    else:
        raise Http404


@login_required
def clear_database(request, anim_id):
    if get_object_or_404(Profile,user=request.user).admin == True:
        anime = get_object_or_404(anim, id=anim_id)
        for photo in anime.anim_video_set.all():
            s3 = boto3.client('s3',
                endpoint_url=LIARA['endpoint'],
                aws_access_key_id=LIARA['accesskey'],
                aws_secret_access_key=LIARA['secretkey']
            )
            bucket_name = LIARA['bucket']
            s3.delete_object(Bucket=bucket_name, Key='media/' + photo.video.name)
            photo.delete()
        return redirect(request.POST.get('next'))
    else:
        raise Http404

@login_required
def delete(request):
    if get_object_or_404(Profile,user=request.user).admin == True:
        response_data = {}
        
        if request.POST.get('action') == 'post':
            video = anim_video.objects.get(id=request.POST.get('video_id'))
            s3 = boto3.client('s3',
                endpoint_url=LIARA['endpoint'],
                aws_access_key_id=LIARA['accesskey'],
                aws_secret_access_key=LIARA['secretkey']
            )
            bucket_name = LIARA['bucket']
            s3.delete_object(Bucket=bucket_name, Key=video.video.name)
            video.delete()
            response_data['saved'] = True
            return JsonResponse(response_data)
    else:
        raise Http404


control_panel/templates/list/accounts.html
{% extends 'upload/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}Episod{% endblock %}



{% block content %}
  <a href="{% url 'ControlPanel:create' %}"  type="submit" class="btn btn-success pull-right">
    <span class="glyphicon glyphicon-pencel"></span> {% trans 'Add Anime' %}
  </a>
  <h1 class="page-header">
    {% trans 'ControlPanel' %}
    <small>/{% trans 'Accounts' %}</small>
  </h1>

<div class="row">
<div class='col-md-9'>
<table id="gallery" class="table table-bordered">
  <thead>
    <tr>
      <th>{% trans 'Photo' %}</th>
      <th>{% trans 'UserName' %}</th>
      <th>{% trans 'Bio' %}</th>
	  <th>{% trans 'Information' %}</th>
      <th>{% trans 'Settings' %}</th>
	  <th>{% trans 'translator' %}</th>
    </tr>
  </thead>
  
  <tbody>
    {% for profile in profiles %}
      <tr id="anim-{{ profile.id }}">
        <td style="width: 100px;">
          <img src="{{ profile.photo.url }}" alt="" style="width: 100%;">
          <p id="error-{{ profile.id }}"></p>
        </td>
        <td><a href="{}">{{ profile }}</a></td>
        <td>
        <p>{{ profile.bio }}</p>
        </td>
		<td>
        <p>{% trans 'Followers' %}: {{ profile.user.followers.count|add:-1 }}</p>
		<p>{% trans 'Following' %}: {{ profile.user.following.count|add:-1 }}</p>
        </td>
        <td>
        {% csrf_token %}
        <a href="" type="button" class="btn btn-success" ><span class="glyphicon glyphicon-eye-open">{% trans 'See' %}</span></a>
        <a href="" type="button" class="btn btn-success" ><span class="glyphicon glyphicon-edit">{% trans 'Edit' %}</span></a>
	  </td>
	  <td>
	    <button type="button" onclick="set_active({{profile.id}})" id='status-{{profile.id}}' class="btn {% if profile.admin %}btn-success{% else %} btn-danger {% endif %}" {% if request.user.is_staff %} {% else %} disabled {% endif %}><span id='label-{{profile.id}}' class="glyphicon {% if profile.admin %}glyphicon-eye-open{% else %}glyphicon-eye-close{% endif %}">{% if profile.admin %}{% trans 'Active' %}{% else %}{% trans 'Inactive' %}{% endif %}</span></button>
	  </td>
      </tr>
    {% endfor %}
  </tbody>
</table>
</div>
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">{% trans 'ControlPanel' %}</h3>
        </div>
        <div class="list-group">
		  <a href="{% url 'ControlPanel:home' %}" class="list-group-item{% if request.path == '/ControlPanel/' %} active{% endif %}">
            {% trans 'Animes' %}
          </a>
          <a href="{% url 'ControlPanel:accounts' %}" class="list-group-item{% if request.path == '/ControlPanel/accounts/' %} active{% endif %}">
            {% trans 'Accounts' %}
          </a>
          <a href="" class="list-group-item{% if request.path == '/ControlPanel/blogs/' %} active{% endif %}">
            {% trans 'Blogs' %}
          </a>
        </div>
      </div>
    </div>
</div>
<script>
  function getCookie(cname) {
    var name = cname + "=";
    var ca = document.cookie.split(';');
    for(var i = 0; i < ca.length; i++) {
      var c = ca[i];
      while (c.charAt(0) == ' ') {
        c = c.substring(1);
      }
      if (c.indexOf(name) == 0) {
        return c.substring(name.length, c.length);
      }
    }
    return "";
  }

    function set_active(id){
      var input = document.getElementById("status-"+id);
	  var label = document.getElementById("label-"+id);
      $.ajax({
        type:'post',
        url: "{% url 'ControlPanel:set_admin' %}",
        headers: {'X-CSRFToken': getCookie('csrftoken')},
        data:{
            accepted:{% if anim.accepted == True %} "True" {%else%} "False" {%endif%},
            id:id,
            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
            action: 'post'
        },
        
        success: function(response) {
		  if (response.is_valid){
			input.classList.remove("btn-success");
			input.classList.remove("btn-danger");
			input.classList.add("btn-success");
			label.classList.remove("glyphicon-eye-open");
			label.classList.remove("glyphicon-eye-close");
			label.classList.add("glyphicon-eye-open");
			label.innerText = "{% trans 'Active' %}"; 
		 }else{
			input.classList.remove("btn-success");
			input.classList.remove("btn-danger");
			input.classList.add("btn-danger");
			label.classList.remove("glyphicon-eye-open");
			label.classList.remove("glyphicon-eye-close");
			label.classList.add("glyphicon-eye-close");
			label.innerText = "{% trans 'Inactive' %}"; 
		 }
         },
        
        error: function(response) {
            console.log('error');
        }
    });
      
    };
</script>
{% endblock %}

control_panel/templates/list/anims.html
{% extends 'upload/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}Episod{% endblock %}



{% block content %}
  <a href="{% url 'ControlPanel:create' %}"  type="submit" class="btn btn-success pull-right">
    <span class="glyphicon glyphicon-pencel"></span> {% trans 'Add Anime' %}
  </a>
  <h1 class="page-header">
    {% trans 'ControlPanel' %}
    <small>/{% trans 'Accounts' %}</small>
  </h1>


<div class="row">

<div class='col-md-9'>
<table id="gallery" class="table table-bordered">
  <thead>
    <tr>
      <th>{% trans 'Photo' %}</th>
      <th>ن{% trans 'Anime Name' %}</th>
	  <th>{% trans 'Information' %}</th>
      <th>{% trans 'Settings' %}</th>
    </tr>
  </thead>
  
  <tbody>
    {% for anim in anims %}
      <tr id="anim-{{ anim.id }}">
        <td style="width: 100px;">
          <img src="{{ anim.photo.url }}" alt="" style="width: 100%;">
          <p id="error-{{ anim.id }}"></p>
        </td>
        <td><a style='word-break: break-word;' href="{% url 'anime:view' anim_name=anim.name_Japanese %}">{{ anim.name_Japanese }}</a></td>
        <td>
        <p style='word-break: break-word;'>{{ anim.description | truncatewords:50 }}</p>
        </td>
        <td>
        {% csrf_token %}
        <a href="{% url 'anime:view' anim_name=anim.name_Japanese %}" type="button" class="btn btn-success" ><span class="glyphicon glyphicon-eye-open">{% trans 'See' %}</span></a>
        <a href="{% url 'ControlPanel:edit' anim.id %}" type="button" class="btn btn-success" ><span class="glyphicon glyphicon-edit">{% trans 'Edit' %}</span></a>
        <button type="button" onclick="set_active({{anim.id}})" id='status-{{anim.id}}' class="btn {% if anim.accepted %}btn-success{% else %} btn-danger {% endif %}" {% if request.user.is_staff %} {% else %} disabled {% endif %}><span id='label-{{anim.id}}' class="glyphicon {% if anim.accepted %}glyphicon-eye-open{% else %}glyphicon-eye-close{% endif %}">{% if anim.accepted %}{% trans 'Active' %}{% else %}{% trans 'Inactive' %}{% endif %}</span></button>
        <a href="{% url 'ControlPanel:upload' anim.id %}" type="button" class="btn btn-success" ><span class="glyphicon glyphicon-edit">{% trans 'Add New Episod' %}</span></a>
	  </td>
      </tr>
    {% endfor %}
  </tbody>
</table>
</div>
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">{% trans 'ControlPanel' %}</h3>
        </div>
        <div class="list-group">
		  <a href="{% url 'ControlPanel:home' %}" class="list-group-item{% if request.path == '/ControlPanel/' %} active{% endif %}">
            {% trans 'Animes' %}
          </a>
          <a href="{% url 'ControlPanel:accounts' %}" class="list-group-item{% if request.path == '/ControlPanel/accounts/' %} active{% endif %}">
            {% trans 'Accounts' %}
          </a>
          <a href="" class="list-group-item{% if request.path == '/ControlPanel/blogs/' %} active{% endif %}">
            {% trans 'Blogs' %}
          </a>
        </div>
      </div>
    </div>
</div>
<script>
  function getCookie(cname) {
    var name = cname + "=";
    var ca = document.cookie.split(';');
    for(var i = 0; i < ca.length; i++) {
      var c = ca[i];
      while (c.charAt(0) == ' ') {
        c = c.substring(1);
      }
      if (c.indexOf(name) == 0) {
        return c.substring(name.length, c.length);
      }
    }
    return "";
  }

    function set_active(id){
      var input = document.getElementById("status-"+id);
	  var label = document.getElementById("label-"+id);
      $.ajax({
        type:'post',
        url: "{% url 'ControlPanel:change_active_status' %}",
        headers: {'X-CSRFToken': getCookie('csrftoken')},
        data:{
            accepted:{% if anim.accepted == True %} "True" {%else%} "False" {%endif%},
            id:id,
            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
            action: 'post'
        },
        
        success: function(response) {
		  if (response.is_valid){
			input.classList.remove("btn-success");
			input.classList.remove("btn-danger");
			input.classList.add("btn-success");
			label.classList.remove("glyphicon-eye-open");
			label.classList.remove("glyphicon-eye-close");
			label.classList.add("glyphicon-eye-open");
			label.innerText = "{% trans 'Active' %}"; 
		 }else{
			input.classList.remove("btn-success");
			input.classList.remove("btn-danger");
			input.classList.add("btn-danger");
			label.classList.remove("glyphicon-eye-open");
			label.classList.remove("glyphicon-eye-close");
			label.classList.add("glyphicon-eye-close");
			label.innerText = "{% trans 'Inactive' %}"; 
		 }
         },
        
        error: function(response) {
            console.log('error');
        }
    });
      
    };
</script>
{% endblock %}