anifilms/urls.py
from django.contrib import admin
from django.urls import path , re_path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from user import views as user_views
from user.forms import LoginForm
from django.contrib.auth import views as auth_views
from anim import views
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('ControlPanel/', include('control_panel.urls')),
    path('accounts/',include('user.urls')),
    path('',include('anim.urls')),
    path('api/', include('api.urls'), name='api'),
    path('comment/', include('comment.urls')),
    path('rating/', include('rating.urls')),
    path('rosetta/', include('rosetta.urls')),
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/urls.py
from . import views
from django.urls import path

app_name = 'api'

urlpatterns = [
    path('anime/', views.AnimeListView.as_view(), name='anime-list'),
]

comment/urls.py
from django.urls import path
from comment import views

app_name = 'comment'
urlpatterns = [
    path('detail/', views.CommentDetail.as_view(), name='detail'),
    path('list/', views.CommentList.as_view(), name='list'),
    path('create/', views.CommentCreate.as_view(), name='create'),
    path('update/', views.CommentUpdate.as_view(), name='update'),
    path('delete/<str:urlhash>/', views.CommentDelete.as_view(), name='delete'),
    path('react/', views.CommentReact.as_view(), name='react'),
]

rating/urls.py
from django.urls import path

from rating import views

app_name = 'rating'
urlpatterns = [
    path('create/', views.UserRatingCreate.as_view(), name='create'),
    path('info/<str:urlhash>/', views.RatingInfo.as_view(), name='info'),
]

comment/models.py
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.html import format_html

from comment.managers import CommentQuerySet, ReactionQuerySet

User = get_user_model()


class CommentSettings(models.Model):
    name = models.CharField(max_length=30)
    slug = models.SlugField(primary_key=True, help_text='This value will be used in render_comments tag')

    default_profile_image = models.ImageField(upload_to='comment_default_profile_images', null=True, blank=True)
    content_words_count = models.PositiveSmallIntegerField(default=40, help_text='More than this value will have Read More button in comment content')
    status_check = models.BooleanField(default=False, help_text='If True, comment status will be set as d(Delivered) otherwise it will be set as a(Accepted).')
    status_edited_check = models.BooleanField(default=False, help_text='If True, comment status_edited will be set as d(Delivered) otherwise it will be set as a(Accepted) when a comment is edited.')
    allow_spoiler = models.BooleanField(default=True)
    allow_reply = models.BooleanField(default=True)
    allow_edit = models.BooleanField(default=True)
    allow_delete = models.BooleanField(default=True)
    allow_reaction = models.BooleanField(default=True, help_text='First, create a react emoji in React models')
    reaction_type = models.CharField(max_length=6, choices=(('emoji', 'Emoji'), ('source', 'Source')), default='emoji', help_text='Add source in React model')
    per_page = models.PositiveSmallIntegerField(default=10, help_text='Set 0 if you don\'t want pagination (All comments will be shown at once)')
    time_type = models.PositiveSmallIntegerField(default=1, choices=((1, 'Compound'), (2, 'From Now'), (3, 'Date & Time')), help_text='Comment posted time style')
    time_days = models.PositiveSmallIntegerField(default=3, help_text='Less than this value will use FROM NOW type , more will use DATE & TIME type')
    theme_direction = models.CharField(max_length=3, choices=(('ltr', 'LTR (Left to Right)'), ('rtl', 'RTL (Right to Left)')), default='ltr')
    theme_dark_mode = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Comment Settings'
        verbose_name_plural = 'Comment Settings'

    def __str__(self):
        return f'{self.name} - [{self.slug}]'


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    content_main = models.TextField()
    content = models.TextField()  # edited content will store here
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='children', null=True, blank=True)
    is_spoiler = models.BooleanField(default=False)
    is_pinned = models.BooleanField(default=False)
    STATUS_CHOICES = (('d', 'Delivered'), ('a', 'Accepted'), ('r', 'Rejected'))
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='d')
    STATUS_EDITED_CHOICES = (('n', 'None'), ('d', 'Delivered'), ('a', 'Accepted'), ('r', 'Rejected'))
    status_edited = models.CharField(max_length=1, choices=STATUS_EDITED_CHOICES, default='n')
    urlhash = models.CharField(max_length=50, unique=True, editable=False)
    posted = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    objects = CommentQuerySet.as_manager()

    class Meta:
        ordering = ('-is_pinned', '-posted')

    def __str__(self):
        if not self.parent:
            return f'{self.content_main[:20]}'
        else:
            return f'[RE] ({self.parent.content_main[:10]}) : {self.content_main[:15]}'

    def set_unique_urlhash(self):
        if not self.urlhash:
            self.urlhash = self.__class__.objects.generate_urlhash()
            while self.__class__.objects.filter(urlhash=self.urlhash).exists():
                self.urlhash = self.__class__.objects.generate_urlhash()

    def save(self, *args, **kwargs):
        self.set_unique_urlhash()
        super(Comment, self).save(*args, **kwargs)

    def is_updated(self):
        return True if self.updated.timestamp() > self.posted.timestamp() and self.status_edited == 'a' else False

    is_updated.boolean = True

    @property
    def is_parent(self):
        return self.parent is None


class React(models.Model):
    slug = models.CharField(max_length=20, unique=True)
    emoji = models.CharField(max_length=5)
    source = models.ImageField(upload_to='react_source', null=True, blank=True)

    def __str__(self):
        return self.slug

    def source_file(self):
        return format_html(f"<img style='height:20px' src='{self.source.url}' alt='{self.emoji}'>") if self.source else 'X'


class Reaction(models.Model):
    user = models.ForeignKey(User, related_name='comment_reactions', on_delete=models.CASCADE, editable=False)
    comment = models.ForeignKey(Comment, related_name='reactions', on_delete=models.CASCADE, editable=False)
    react = models.ForeignKey(React, related_name='reactions', on_delete=models.CASCADE, editable=False)

    objects = ReactionQuerySet.as_manager()

    class Meta:
        unique_together = ['user', 'comment']

    def __str__(self):
        return f'{self.user} <{self.react.slug}> ({self.comment.content_main[:20]})'

comment/forms.py
from django import forms
from comment.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', 'is_spoiler')

comment/views.py
import json

from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse, HttpResponse, HttpResponseBadRequest
from django.shortcuts import render
from django.utils import timezone
from django.views import View
from django.views.generic import ListView, TemplateView

from comment.forms import CommentForm
from comment.mixins import CommentMixin
from comment.models import Comment, Reaction, React, CommentSettings


class CommentDetail(TemplateView):
    template_name = 'comment/comment/comment_body.html'

    def get(self, request, *args, **kwargs):
        urlhash = request.GET.get('urlhash')
        settings_slug = request.GET.get('settings_slug')
        context = {
            'comment': Comment.objects.get(urlhash=urlhash),
            'settings': CommentSettings.objects.get(slug=settings_slug)
        }
        return render(request, self.template_name, context=context)


class CommentList(ListView):
    context_object_name = 'comments'
    template_name = 'comment/comment/comment_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        settings_slug = self.request.GET.get('settings_slug')
        context['settings'] = CommentSettings.objects.get(slug=settings_slug)
        return context

    def get_queryset(self):
        queryset = None
        if self.request.GET:
            app_name = self.request.GET.get('app_name')
            model_name = self.request.GET.get('model_name')
            object_id = self.request.GET.get('object_id')
            settings_slug = self.request.GET.get('settings_slug')
            comment_settings = CommentSettings.objects.get(slug=settings_slug)
            content_type = ContentType.objects.get(app_label=app_name, model=model_name.lower())
            queryset = Comment.objects.filter(content_type=content_type, object_id=object_id)
            queryset = queryset.filter_accepted().filter_parents()
            queryset = queryset.order_pinned_newest()

            # Pagination
            page = self.request.GET.get('page', 1)
            if comment_settings.per_page == 0:
                paginator = Paginator(queryset, queryset.count())
            else:
                paginator = Paginator(queryset, comment_settings.per_page)
            try:
                queryset = paginator.page(page)
            except PageNotAnInteger:
                queryset = paginator.page(1)
            except EmptyPage:
                queryset = paginator.page(paginator.num_pages)

        return queryset


class CommentCreate(CommentMixin, View):
    def post(self, request, *args, **kwargs):
        data = json.loads(request.body)
        form = CommentForm(data=data)
        if form.is_valid():
            comment = form.save(commit=False)

            comment.user = request.user
            comment.content_main = comment.content
            app_name = data.get('app_name', None)
            model_name = data.get('model_name', None)
            object_id = data.get('object_id', None)
            parent_id = data.get('parent_id', None)
            settings_slug = data.get('settings_slug', None)
            comment_settings = CommentSettings.objects.get(slug=settings_slug)
            time_posted = timezone.now()
            comment.content_type = ContentType.objects.get(app_label=app_name, model=model_name.lower())
            comment.object_id = object_id

            if parent_id:
                parent_comment = Comment.objects.get(urlhash=parent_id)
                comment.parent = parent_comment
            else:
                comment.parent = None
            comment.posted = time_posted

            if not comment_settings.status_check:
                comment.status = 'a'

            comment.save()
            return HttpResponse(status=200)
        else:
            return HttpResponseBadRequest()


class CommentUpdate(CommentMixin, View):
    def post(self, request, *args, **kwargs):
        data = json.loads(request.body)
        form = CommentForm(data=data)
        if form.is_valid():
            comment = Comment.objects.get(urlhash=data.get('urlhash'))
            new_content = data.get('content')
            new_is_spoiler = data.get('is_spoiler')
            if comment.content_main != new_content or comment.is_spoiler != new_is_spoiler:
                comment.content = new_content
                comment.is_spoiler = new_is_spoiler

                settings_slug = data.get('settings_slug', None)
                comment_settings = CommentSettings.objects.get(slug=settings_slug)

                if comment_settings.status_edited_check and comment.content_main != comment.content:
                    comment.status_edited = 'd'
                    comment.save()
                else:
                    comment.status_edited = 'a'
                    comment.content_main = comment.content
                    comment.save()

                return JsonResponse({'urlhash': comment.urlhash}, status=200)
            return HttpResponse(status=200)
        else:
            return HttpResponseBadRequest()


class CommentDelete(CommentMixin, View):
    def get(self, request, urlhash, *args, **kwargs):
        return render(request, 'comment/forms/comment_form_delete.html', context={'urlhash': urlhash})

    def post(self, request, urlhash, *args, **kwargs):
        comment = Comment.objects.get(urlhash=urlhash)
        if comment:
            comment.delete()
            return HttpResponse(status=200)
        return HttpResponseBadRequest()


class CommentReact(CommentMixin, View):
    def get(self, request, *args, **kwargs):
        urlhash = request.GET.get('urlhash')
        context = {'comment': Comment.objects.get(urlhash=urlhash)}
        return render(request, 'comment/comment/comment_reactions.html', context=context)

    def post(self, request, *args, **kwargs):
        user = request.user
        data = json.loads(request.body)
        comment_urlhash = data.get('urlhash', None)
        react_slug = data.get('react_slug', None)

        reaction = Reaction.objects.filter(user=user, comment__urlhash=comment_urlhash).first()

        if reaction:  # Update Previous Reaction
            if reaction.react.slug == react_slug:  # Delete Previous Reaction
                reaction.delete()
            else:  # Change Previous Reaction
                react = React.objects.get(slug=react_slug)
                reaction.react = react
                reaction.save()
        else:  # Create New Reaction
            comment = Comment.objects.get(urlhash=comment_urlhash)
            react = React.objects.get(slug=react_slug)
            Reaction.objects.create(user=user, comment=comment, react=react)

        return HttpResponse(status=200)

comment/templates/comment/comment/comment_body.html
{% load i18n %}
{% load static %}
{% load comment_tags %}
<style>
    .admin {
        border: 1px solid red;
        color: red;
    }

    .admin-label {
        color: red;
    }
</style>
<input type="checkbox" class="peer sr-only" id="toggle-spoiler-{{ comment.urlhash }}">
<div class="flex justify-between">

    {#COMMENT INFO#}
    <div class="h-12 flex items-center">
        <img src="{{ comment.user.user.photo.url }}" alt="Profile" class="inline-block w-12 h-12 rounded-full"/>
        <span class="inline-block align-middle ltr:ml-2 rtl:mr-2 text-lg font-semibold {% if comment.user.user.admin %}admin{% endif %}">
            <span dir="ltr">{{ comment.user.username }}</span>
            {% if comment.user.user.admin %}
                <span class="admin-label">(ادمین)</span>
            {% endif %}
        </span>
        <span class="mx-1 text-comment-time-text-light dark:text-comment-time-text-dark">•</span>
        <span class="text-sm text-comment-time-text-light dark:text-comment-time-text-dark">
            {% if settings.time_type == 1 and comment.posted|is_time_lt_days:settings.time_days %}
                {{ comment.posted|timesince }} {% trans 'ago' %}
            {% elif settings.time_type == 1 and not comment.posted|is_time_lt_days:settings.time_days %}
                {{ comment.posted|date:'SHORT_DATE_FORMAT' }} {{ comment.posted|time:'TIME_FORMAT' }}
            {% elif settings.time_type == 2 %}
                {{ comment.posted|timesince }} {% trans 'ago' %}
            {% elif settings.time_type == 3 %}
                {{ comment.posted|date:'SHORT_DATE_FORMAT' }} {{ comment.posted|time:'TIME_FORMAT' }}
            {% endif %}
        </span>
        <span class="ltr:ml-2 rtl:mr-2 rtl:scale-x-[-1]">
            {% if comment.is_updated %}
                {% include 'comment/icons/icon_pen.html' with class='inline w-3 h-3 fill-icon-pin-light dark:fill-icon-pin-dark' %}
            {% endif %}
        </span>
        <span class="ltr:ml-2 rtl:mr-2 rtl:scale-x-[-1]">
            {% if comment.is_pinned %}
                {% include 'comment/icons/icon_pin.html' with class='inline w-3 h-3 fill-icon-pin-light dark:fill-icon-pin-dark' %}
            {% endif %}
        </span>
    </div>

    {#COMMENT OPTIONS#}
    <div class="grid content-center ltr:mr-1 rtl:ml-1">
        {% if request.user.is_authenticated and comment.user == request.user %}
            {% if comment.is_spoiler or settings.allow_edit or settings.allow_delete %}
                <div class="group flex flex-row-reverse space-x-3 ltr:space-x-reverse rounded-full bg-comment-option-bg-light dark:bg-comment-option-bg-dark p-2 border-2 border-comment-option-border-light dark:border-comment-option-border-dark">
                    {% include 'comment/icons/icon_dots.html' with class='inline w-6 h-6 fill-icon-dots-light dark:fill-icon-dots-dark' %}
                    {% if settings.allow_edit %}
                        <label for="toggle-edit-{{ comment.urlhash }}" class="hidden group-hover:inline">{% include 'comment/icons/icon_edit.html' with class='w-6 h-6 cursor-pointer fill-icon-edit-light dark:fill-icon-edit-dark' %}</label>
                    {% endif %}
                    {% if settings.allow_delete %}
                        <span onclick="LoadDeleteCommentForm('{{ comment.urlhash }}')" class="hidden group-hover:inline">{% include 'comment/icons/icon_delete.html' with class='w-6 h-6 cursor-pointer fill-icon-delete-light dark:fill-icon-delete-dark' %}</span>
                    {% endif %}
                    {% if comment.is_spoiler %}
                        {% include 'comment/icons/icon_eye_off.html' with class='hidden w-6 h-6 fill-none fill-icon-spoiler-option-light dark:fill-icon-spoiler-option-dark group-hover:inline' %}
                    {% endif %}
                </div>
            {% endif %}
        {% elif comment.is_spoiler %}
			
            <label for="toggle-spoiler-{{ comment.urlhash }}" class="rounded-full p-2 cursor-pointer border-2 bg-comment-option-bg-light dark:bg-comment-option-bg-dark border-comment-option-border-light dark:border-comment-option-border-dark">
                {% include 'comment/icons/icon_eye.html' with class='inline w-6 h-6 fill-none stroke-icon-spoiler-light dark:stroke-icon-spoiler-dark' %}
            </label>
        {% endif %}
    </div>
</div>

{#COMMENT SECTION#}
<div class="mt-2 {% if comment.is_spoiler and not comment.user == request.user %}hidden peer-checked:block{% endif %}">
    {#COMMENT CONTENT#}
    {% if settings.allow_edit %}<input type="checkbox" class="peer sr-only" id="toggle-edit-{{ comment.urlhash }}">{% endif %}
    <div class="p-2 text-justify block peer-checked:hidden">
        {#CONTENT#}
        {% if comment.content_main|wordcount > settings.content_words_count %}
            <input type="checkbox" class="peer sr-only" id="toggle-more-{{ comment.urlhash }}">
            <div class="whitespace-pre-wrap text-black dark:text-white inline-block peer-checked:hidden {% if LANGUAGE_CODE == 'fa-ir' %}font-default-fd{% else %}font-default{% endif %}">{{ comment.content_main|truncatewords:settings.content_words_count }}</div>
            <div class="whitespace-pre-wrap text-black dark:text-white hidden peer-checked:block {% if LANGUAGE_CODE == 'fa-ir' %}font-default-fd{% else %}font-default{% endif %}">{{ comment.content_main }}</div>
            <label for="toggle-more-{{ comment.urlhash }}" class="inline peer-checked:hidden cursor-pointer text-comment-read-more-light dark:text-comment-read-more-dark">{% trans 'Read More' %} {% include 'comment/icons/icon_down.html' with class='w-6 inline-block' %}</label>
            <label for="toggle-more-{{ comment.urlhash }}" class="hidden peer-checked:block cursor-pointer text-comment-read-more-light dark:text-comment-read-more-dark">{% trans 'Read Less' %} {% include 'comment/icons/icon_up.html' with class='w-6 inline-block' %}</label>
        {% else %}
            <div class="whitespace-pre-wrap text-black dark:text-white {% if LANGUAGE_CODE == 'fa-ir' %}font-default-fd{% else %}font-default{% endif %}">{{ comment.content_main }}</div>
        {% endif %}
    </div>
    <div class="text-justify hidden peer-checked:block">
        {% if request.user.is_authenticated and comment.user == request.user and settings.allow_edit %}
            {% include 'comment/forms/comment_form_edit.html' with comment=comment settings=settings %}
        {% endif %}
    </div>

    <div class="mt-2 flex justify-between">

        {#COMMENT REACTION#}
        <div class="flex space-x-2">
            {% if settings.allow_reaction %}
                <form id="form-comment-react-{{ comment.urlhash }}" method="post" action="{% url 'comment:react' %}">{% csrf_token %}
                    <div id="comment-react-list">
                        {% include 'comment/comment/comment_reactions.html' %}
                    </div>
                </form>
            {% endif %}
        </div>

        {#COMMENT REPLY#}
        {% if settings.allow_reply and comment.is_parent %}
            {% with count_children=comment.children.filter_accepted.count %}
                <label for="toggle-reply-{{ comment.urlhash }}" class="grid self-center">
                <span class="cursor-pointer text-reply-text-light dark:text-reply-text-dark px-1">
                    {% if count_children > 1 %}
                        {{ count_children|number }} {% trans 'Replies' context 'reply-count' %}
                    {% elif count_children == 1 %}
                        {{ count_children }} {% trans 'Reply' context 'reply-count' %}
                    {% else %}
                        {% trans 'Reply' context 'verb' %}
                    {% endif %}
                </span>
                </label>
            {% endwith %}
        {% endif %}
    </div>
</div>

comment/templates/comment/comment/comment_counter.html
{% load i18n %}
{% load comment_tags %}

<div class="my-4 border-b-4 border-section-primary-light dark:border-section-primary-dark pb-2">
  <span class="border-b-4 border-section-secondary-light dark:border-section-secondary-dark pb-2 font-semibold text-section-text-light dark:text-section-text-dark">
    <span class="px-2">{% trans 'Comments' %}</span>
      {% if count %}
          <span class="rounded-md bg-section-number-bg-light text-section-number-text-light dark:section-number-bg-dark dark:section-number-text-dark px-1">{{ count|number:1 }}</span>
      {% endif %}
  </span>
</div>

comment/templates/comment/comment/comment_list.html
{# COMMENTS COUNT #}
{% include 'comment/comment/comment_counter.html' with count=comments.paginator.count %}

<div class="flex flex-col space-y-2">
    {% for comment in comments.object_list %}
        <div class="flex flex-col space-y-2">

            {% if settings.allow_reply %}<input type="checkbox" class="peer sr-only" name="reply-section" id="toggle-reply-{{ comment.urlhash }}">{% endif %}
            {# PARENT #}
            <div id="comment-{{ comment.urlhash }}" class="rounded-lg border-2 bg-comment-parent-bg-light border-comment-parent-border-light p-2 dark:bg-comment-parent-bg-dark dark:border-comment-parent-border-dark">
                {% include 'comment/comment/comment_body.html' with comment=comment %}
            </div>

            {#ALLOW_REPLY#}
            {% if settings.allow_reply %}

                {# REPLY SECTION #}
                <div class="hidden border-reply-border-light dark:border-reply-border-dark m-4 ltr:border-l-2 rtl:border-r-2 ltr:mr-0 rtl:ml-0 ltr:pl-4 rtl:pr-4 peer-checked:block">

                    <div class="flex flex-col space-y-2">
                        {# CHILDREN #}
                        {% for child in comment.children.filter_accepted.order_pinned_oldest %}
                            <div id="comment-{{ child.urlhash }}" class="rounded-lg border-2  bg-comment-child-bg-light border-comment-child-border-light p-2 dark:border-comment-child-border-dark dark:bg-comment-child-bg-dark">
                                {% include 'comment/comment/comment_body.html' with comment=child %}
                            </div>
                        {% endfor %}

                        {# REPLY-FORM #}
                        {% include 'comment/forms/comment_form_reply.html' with comment=comment page=comments.number %}

                    </div>
                </div>
            {% endif %}

        </div>
    {% empty %}
        {% include 'comment/utils/comment_list_empty.html' %}
    {% endfor %}

    {#PAGINATION#}
    {% if comments.paginator.num_pages != 1 %}
        {% include 'comment/utils/comment_list_pagination.html' with paginator=comments %}
    {% endif %}
</div>

comment/templates/comment/comment/comment_reactions.html
{% load comment_tags %}

{% for react, reaction in comment.reactions.get_reacts.items %}
    <button type="button" {% if request.user.is_authenticated %} onclick="ReactComment('{{ comment.urlhash }}', '{{ react.slug }}')" {% endif %}
            class="group h-12 rounded-full border-2 py-2 px-2 {% if request.user in reaction.get_users %}border-react-selected-border-light bg-react-selected-bg-light dark:border-react-selected-border-dark dark:bg-react-selected-bg-dark{% else %}border-react-default-border-light bg-react-default-bg-light dark:border-react-default-border-dark dark:bg-react-default-bg-dark{% endif %}">
        {% if settings.reaction_type == 'source' and react.source %}
            <img src="{{ react.source.url }}" alt="{{ react.emoji }}" class="w-6 h-6 inline transition-transform duration-200 origin-bottom group-hover:scale-150">
        {% else %}
            <span class="w-6 h-6 inline text-base">{{ react.emoji }}</span>
        {% endif %}
        {% if reaction.count %} <span class="ltr:pr-1 rtl:pl-1 text-react-count-text-light dark:text-react-count-text-dark">{{ reaction.count|number:0 }}</span>{% endif %}
    </button>
{% endfor %}

comment/templates/comment/comment/comments.html
{% load static %}
{% load comment_tags %}

{% render_comment_import %}

{% get_settings 'LANGUAGE_CODE' as LANGUAGE_CODE %}

<div {% if settings.theme_dark_mode %} data-mode="dark" {% endif %} dir="{{ settings.theme_direction }}">
    <div id="comments" class="p-4 bg-background-light dark:bg-background-dark {% if LANGUAGE_CODE == 'fa-ir' %}font-default-fd{% endif %}">

        {# COMMENT MODAL #}
        <div id="comment-modal"></div>

        {# CREATE COMMENT FORM #}
        {% include 'comment/forms/comment_form_create.html' with settings=settings %}

        {# COMMENTS LIST #}
        <div id="comment-list">
            {% include 'comment/utils/comment_list_loader.html' %}
        </div>

    </div>
</div>
{% include 'comment/utils/toast.html' %}
{% include 'comment/utils/SCRIPTS.html' %}

comment/templates/comment/comment/object_info.html
<input type="hidden" name="app_name" value="{{ object_info.app_name }}" hidden>
<input type="hidden" name="object_id" value="{{ object_info.object_id }}" hidden>
<input type="hidden" name="model_name" value="{{ object_info.model_name }}" hidden>
<input type="hidden" name="content_type" value="{{ object_info.content_type }}" hidden>
<input type="hidden" name="settings_slug" value="{{ settings.slug }}" hidden>