anim/urls.py
from django.urls import path, re_path, include
from . import views
from user import views as user_views

app_name = 'anime'


urlpatterns = [
    path('',views.list, name='list'),
    path('video/<int:video_id>',views.view_video, name='video'),
    path('<str:anim_name>',views.view, name='view'),
    path('tag/<str:slug>/', views.tagged, name="tagged"),
    path('save/<int:pk>',views.SaveView, name='anim_save'),
]

api/urls.py
from . import views
from django.urls import path

app_name = 'api'

urlpatterns = [
    path('anime/', views.AnimeListView.as_view(), name='anime-list'),
]

comment/urls.py
from django.urls import path
from comment import views

app_name = 'comment'
urlpatterns = [
    path('detail/', views.CommentDetail.as_view(), name='detail'),
    path('list/', views.CommentList.as_view(), name='list'),
    path('create/', views.CommentCreate.as_view(), name='create'),
    path('update/', views.CommentUpdate.as_view(), name='update'),
    path('delete/<str:urlhash>/', views.CommentDelete.as_view(), name='delete'),
    path('react/', views.CommentReact.as_view(), name='react'),
]

rating/urls.py
from django.urls import path

from rating import views

app_name = 'rating'
urlpatterns = [
    path('create/', views.UserRatingCreate.as_view(), name='create'),
    path('info/<str:urlhash>/', views.RatingInfo.as_view(), name='info'),
]

user/urls.py
from django.urls import path, re_path
from . import views as user_views
from user.forms import LoginForm
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/', user_views.LoginView.as_view(), name='login'),
    path('signup/', user_views.signupView, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('edit/', user_views.editView, name='edit_profile'),
    path('change_password/', user_views.change_password, name='change_password'),
    path('follow/', user_views.followView.as_view(), name='follow'),
    path('<str:username>/', user_views.profileView, name='profile'),
    path('activate/<slug:uidb64>/<slug:token>/', user_views.activate, name='activate'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.signals import user_logged_in, user_logged_out
import PIL.Image as Image
from anim.models import anim
from django.core.validators import RegexValidator


class Subscription(models.Model):
    DURATION_CHOICES = [
        (30, 'یک ماهه'),
        (90, 'سه ماهه'),
        (180, 'شش ماهه'),
        (365, 'یک ساله'),
    ]
    
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    duration = models.IntegerField(choices=DURATION_CHOICES)

    def __str__(self):
        return self.name



class Profile(models.Model):
    LANGUAGE_CHOICES = (
        ('en', 'English'),
        ('fa', 'Farsi'),
   )
    user = models.OneToOneField(User, related_name='user', on_delete=models.CASCADE)
    photo = models.ImageField(_('photo'),default='p_photos/profile.png')
    bio = models.TextField(_('bio'),default='', blank=True)
    admin = models.BooleanField(_('admin'),default=False)
    translator = models.BooleanField(_('translator'),default=False)
    bloger = models.BooleanField(_('bloger'),default=False)
    manager = models.BooleanField(_('manager'),default=False)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+9999999999'. Up to 15 digits allowed.")
    phone = models.CharField(_('phone'),validators=[phone_regex], max_length=17, blank=True)
    telegram = models.URLField(_('telegram'),default='', blank=True)
    language = models.CharField(default='fa', choices=LANGUAGE_CHOICES, max_length=5)
    subscription = models.ForeignKey(Subscription, on_delete=models.SET_NULL, null=True, blank=True)
    subscription_end = models.DateField(_('subscription_end'),null=True, blank=True)
    

    def save(self, *args, **kwargs):
        super().save()

    def __str__(self):
        return f'{self.user.username}'


class DiscountCode(models.Model):
    code = models.CharField(_('code'),max_length=50, unique=True)
    discount = models.DecimalField(_('discount'),max_digits=5, decimal_places=2)
    start_date = models.DateField(_('start_date'))
    end_date = models.DateField(_('end_date'))


class Follow(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')    
    reciever = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followers')
    created_at = models.DateTimeField(_('created_at'),auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        unique_together = ('owner', 'reciever')

        
    def __str__(self):
        return f'{self.owner.username} follows {self.reciever.username}'


class Save(models.Model) :
    owner = models.ForeignKey(User, related_name='save_owner', on_delete=models.CASCADE)    
    anim = models.ForeignKey(anim, on_delete=models.CASCADE, related_name='anim_saves')
    created_at = models.DateTimeField(_('created_at'),auto_now_add=True)

    class Meta:
        unique_together = ('owner', 'anim')

    def __str__(self) :
        return '%s saved %s... post'%(self.owner.username, self.anim.description[:15])



@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        Follow.objects.create(owner=instance, reciever=instance)



@receiver(post_save, sender=User)
def save_profile(sender, instance, **kwargs):
    instance.user.save()
    pass

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from .models import Profile
from django.contrib.auth.forms import PasswordChangeForm


#using first_name as full_name 
class SignupForm(UserCreationForm):
    username   = forms.CharField(widget=(forms.TextInput(attrs={'class': 'border rounded w-full py-2 px-3', 'placeholder': _('enter username')})),label='')
    first_name = forms.CharField(widget=(forms.TextInput(attrs={'class': 'border rounded w-full py-2 px-3', 'placeholder': _('enter first name')})),label='', max_length=32)
    email      = forms.EmailField(widget=(forms.EmailInput(attrs={'class': 'border rounded w-full py-2 px-3', 'placeholder': _('enter email')})),label='', max_length=64)
    password1  = forms.CharField(widget=(forms.PasswordInput(attrs={'class': 'border rounded w-full py-2 px-3', 'placeholder': _('enter password')})),label='')
    password2  = forms.CharField(widget=(forms.PasswordInput(attrs={'class': 'border rounded w-full py-2 px-3', 'placeholder': _('enter repeat the password')})),label='')

    def clean(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(f"Another account is using {email}")
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("This username isn't available. Please try another.")

        return self.cleaned_data

    class Meta:
        model = User
        fields = ('email', 'first_name','username', 'password1','password2')


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=(forms.TextInput(attrs={'class': 'signup-form', 'placeholder': 'Username'})),label='')
    password = forms.CharField(widget=(forms.PasswordInput(attrs={'class': 'signup-form', 'placeholder': 'Password'})),label='')


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'username', 'email']

    def __init__(self, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)

        self.fields['first_name'].widget = forms.TextInput(attrs={'class': 'user-edit-form','placeholder': 'Name'},)
        self.fields['first_name'].label = 'Name'
        self.fields['username'].widget = forms.TextInput(attrs={'class': 'user-edit-form','placeholder': 'Username'},)
        self.fields['username'].help_text = None
        self.fields['email'].widget = forms.TextInput(attrs={'class': 'user-edit-form','placeholder': 'Email'},)
        self.fields['email'].label = 'Email'


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio','photo']

    def __init__(self, *args, **kwargs):
        super(ProfileEditForm, self).__init__(*args, **kwargs)

        self.fields['bio'].widget = forms.TextInput(attrs={'class': 'user-edit-form','placeholder': 'Bio'},)


class passwordChangeForm(PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(passwordChangeForm, self).__init__(*args, **kwargs)

        self.fields['old_password'].widget = forms.PasswordInput(attrs={'class': 'text-gray-800','placeholder': 'current passowrd'},)
        self.fields['new_password1'].widget = forms.PasswordInput(attrs={'class': 'text-gray-800','placeholder': 'new passowrd'},)
        self.fields['new_password2'].widget = forms.PasswordInput(attrs={'class': 'text-gray-800','placeholder': 'confirm passowrd'},)

user/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate, update_session_auth_hash,get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, HttpResponseRedirect, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse, HttpResponseNotFound
from django.forms.models import inlineformset_factory
from django.template.loader import render_to_string
from django.urls import reverse
from django.views import View

from .models import Profile
from user.models import Follow
from anim.models import anim, anim_sub,anim_video

# from notification.models import FollowNotification
from .forms import UserEditForm, ProfileEditForm, passwordChangeForm, SignupForm, LoginForm

from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError
from django.core.exceptions import PermissionDenied
import json
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.utils import translation


def check_lang(request):
    if request.user.is_authenticated:
        translation.activate(request.user.user.language)


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


def signupView(request):
    check_lang(request)
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activation link has been sent to your email id'
            message = render_to_string('user/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                 'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            messages.info(request,'لینک تایید ایمیل برای شما ارسال شد. لطفا ایمیل خود را چک کنید')
            return redirect('anime:list')

    else:
        form = SignupForm()
    return render(request,'user/signup.html', {'form':form})

def activate(request, uidb64, token):
    check_lang(request)
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request,user)
        messages.success(request,'حساب شما با موفقیت تایید شد.')
        return redirect('anime:list')
    else:
        messages.error(request,'این لینک نامعتبر است.')
        return redirect('anime:list')


class LoginView(LoginView):
    template_name="user/login.html"
    
    def form_valid(self, form):
        messages.success(self.request, 'شما با موفقیت وارد شدید.')
        return super().form_valid(form)
    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        return super().get_success_url()


@method_decorator(csrf_exempt, name='dispatch')
class followView(View):

    def post(self, request):
        user_name = request.POST.get('username')
        user2 = User.objects.get(username=user_name)

        following_queryset = request.user.following.all()
        following = [follow.reciever.username for follow in following_queryset]

        if(user2.username in following):
            u = Follow.objects.get(owner=request.user, reciever=user2).delete()
            followed = False
        else:
            u = Follow.objects.get_or_create(owner=request.user, reciever=user2)[0]
            # notification = FollowNotification.objects.create(follow=u)
            followed = True

        html = render_to_string(
            template_name="user/follow.html",
            context={'following':following, 'profile':user2}
        )
        response_data = {}
        response_data['html'] = html
        if request.POST.get("operation") == "follow" and is_ajax(request=request):
            ctx={"followed":followed,"content_id":user_name}
            return HttpResponse(json.dumps(ctx), content_type='application/json')
        return JsonResponse(response_data)    


def followers(request, username):
    check_lang(request)
    profile = get_object_or_404(Profile, user__username=username)
    following_queryset = profile.user.following.all()
    following = [follow.reciever.username for follow in following_queryset]
    return render(request,'user/follow-re-ing.html',{'profile':profile,'following':following,'follow':'followers'})

def following(request, username):
    check_lang(request)
    profile = get_object_or_404(Profile, user__username=username)
    following_queryset = profile.user.following.all()
    following = [follow.reciever.username for follow in following_queryset]
    return render(request,'user/follow-re-ing.html',{'profile':profile,'following':following,'follow':'following'})
    
    
  
@login_required
def profileView(request, username):
    check_lang(request)
    profile = get_object_or_404(Profile, user__username=username)
    saves = request.user.save_owner.all()
    anims_save = [s.anim for s in saves]
    following_queryset = request.user.following.all()
    following = [follow.reciever.username for follow in following_queryset]
    Anim_videos = anim_video.objects.filter(added_by=profile.user).values('anim').distinct()
    Anim_subs = anim_sub.objects.filter(added_by=profile.user).values('anim').distinct()
    anims = anim.objects.filter(id__in=Anim_videos) | anim.objects.filter(id__in=Anim_subs)
    return render(request, 'user/profile.html',{'profile':profile,'following':following, 'anims':anims, 'saves':anims_save})




@login_required
def editView(request):
    check_lang(request)
    if request.method == 'POST':
        u_form = UserEditForm(request.POST, instance=request.user)
        p_form = ProfileEditForm(request.POST, request.FILES, instance=request.user.user)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect('accounts:profile',request.user.username)
    else:
        u_form = UserEditForm(instance=request.user)
        p_form = ProfileEditForm(instance=request.user.user)
    context = {
        'u_form':u_form,
        'p_form':p_form,
        'user_image':request.user.user.photo.url,
    }

    return render(request, 'user/edit.html', context)



@login_required
def change_password(request):
    check_lang(request)
    if request.method == 'POST':
        form = passwordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'رمز عبور شما با موفقیت تغییر کرد')
            return redirect('change_password')
        else:
            messages.error(request, 'لطفاً مطمئن شوید که هر دو رمز عبور مطابقت دارند.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'user/change_password.html', {
        'form': form
    })

user/templates/user/edit.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}Edit Profile &#8226; ANIFILMS {% endblock %}


{% block content %}
<div class="flex flex-wrap justify-center mt-5 pt-4 bg-gray-900 text-white min-h-screen dir-rtl">
    <div class='hidden md:block w-3/12 p-0'>
        <ul class='list-none p-0'>
            <a href="{% url 'accounts:edit_profile' %}" class="text-white no-underline"><li class='py-3 pl-4 border-r-2 border-white font-semibold'>{% trans 'Edit Profile' %}</li></a>
            <a href="{% url 'accounts:change_password' %}" class="text-white no-underline"><li class='py-3 pl-4'>{% trans 'Change Password' %}</li></a>
        </ul>
    </div>
    <div class="w-full md:w-9/12 p-0 md:p-5">
        <div class="w-full pr-5 p-0 text-gray-800">
            <form method="POST" class="pl-5 ml-5" enctype="multipart/form-data">
                {% csrf_token %} 
                <div class='mb-3 text-lg'>
                    <img class='rounded-full w-3/12 text-gray-300' src='{{user_image}}' alt='' style="width: 85px;">
                    <p class='text-white'>{{user.username}}</p>
                </div>
                <div class='mb-3 text-white'>
                    {{p_form.photo}}
                </div>
                <div class='mb-4 flex flex-col'>
                    <label class="font-bold text-white">{% trans 'first name' %}</label>
                    {{ u_form.first_name }}
                </div>
                <div class='mb-4 flex flex-col'>
                    <label class="font-bold text-white">{% trans 'Username' %}</label>
                    {{ u_form.username }}
                </div>
                <div class='mb-4 flex flex-col'>
                    <label class="font-bold text-white">{% trans 'Email' %}</label>
                    {{ u_form.email }}
                </div>
                <div class='mb-4 flex flex-col'>
                    <label class="font-bold text-white">{% trans 'Bio' %}</label>
                    {{p_form.bio}}
                </div>
                <button type="submit" class="px-4 py-2 font-bold text-white bg-blue-500 rounded hover:bg-blue-700">{% trans 'Submit' %}</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

user/templates/user/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}



{% block content %}

<div class="bg-gray-700 p-8 rounded shadow-md w-full max-w-sm mx-auto mt-8 mb-8">
	<div class="text-red-500 mt-2">
        {{ form.errors }}
    </div>
    <h1 class="text-2xl font-bold mb-4 text-white">{% trans 'Login' %}</h1>
    <form method="post" action="{% url 'accounts:login' %}">
        {% csrf_token %}
        <div class="mb-4">
            <label for="username" class="block text-white font-bold mb-2">{% trans 'Login' %}</label>
            <input type="text" id="username" name="username" class="border rounded w-full py-2 px-3" placeholder="{% trans 'Login' %}">
        </div>
        <div class="mb-6">
            <label for="password" class="block text-white font-bold mb-2">{% trans 'Password' %}</label>
            <input type="password" id="password" name="password" class="border rounded w-full py-2 px-3" placeholder="{% trans 'Login' %}">
        </div>
		<input type="hidden" name="next" value="{{ request.GET.next }}">
        <button class="bg-blue-300 hover:bg-blue-100 text-white font-bold py-2 px-4 rounded w-full mb-4">{% trans 'Login' %}</button>
        <div class="text-center">
            <a href="#" class="text-blue-500 hover:underline">{% trans 'forget password' %}</a>
        </div>
        <div class="text-center mt-4 text-white">
            <span>{% trans 'Dont have an account' %}</span> <a href="{% url 'accounts:signup'%}" class="text-blue-500 hover:underline">{% trans 'Register' %}</a>
        </div>
    </form>
</div>


{% endblock %}
 

user/templates/user/profile.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}


{% block head %}

<style>
#translated, #saved {
  transition: opacity 0.5s;
}

.hidden {
  visibility: hidden;
  opacity: 0;
  transition: visibility 0s, opacity 0.5s;
}
	<style>
	/* انیمیشن برای تغییرات در منوی تب */
	#episodes, #comments {
	  transition: opacity 0.5s;
	}

	.hidden {
	  display: none;
	}
	.save-text {
    display: none;
	}

	a:hover .save-text {
		display: inline;
	}
	.save-text {
    display: none;
    transition: all 0.5s ease;
    transform: translateX(-20px);
    opacity: 0;
	}

	a:hover .save-text {
		display: inline;
		transform: translateX(0);
		opacity: 1;
	}
	body {
        background-color: #1A202C;
        color: #E2E8F0;
    }

    .tab-btn {
        padding: 10px 20px;
        font-weight: 600;
        cursor: pointer;
        position: relative;
        overflow: hidden;
        transition: color 0.3s;
		border: 2px solid #6B46C1; /* حاشیه دکمه‌های تب */
    }

    
    

    .tab-content {
        padding: 20px;
        display: none;
        border-top: 2px solid #6B46C1;
    }

    .tab-content.active {
        display: block;
    }

	</style>
</style>
{% endblock %}


{% block content%}


<div class="container mx-auto p-4 text-white" dir='rtl'>
  <div class="flex justify-center items-center">
    <img src="{{ profile.photo.url }}" class="rounded-full w-32 h-32" alt="Profile Image">
  </div>
  <div class="text-center mt-4">
    <h1 class="text-2xl font-bold">{{ profile.user.username }}</h1>
    <p class="mt-2">{{ profile.bio }}</p>
    <div class="mt-4">
      <ul>
        <li class="mb-2">
          <a href="#" class="text-blue-500"><b>{{profile.user.followers.count|add:-1}}</b> {% trans 'Follower' %} {%if profile.user.followers.count > 2%}{% trans 's' %}{% endif %}</a>
          <a href="#" class="text-blue-500"><b>{{profile.user.following.count|add:-1}}</b> {% trans 'Following' %}</a>
        </li>
        <li>
			<span class='follow-section d-inline ml-2'>
				{% if profile.user == user %}
					<a href="{% url 'accounts:edit_profile' %}" class="bg-gray-300 text-gray-700 py-2 px-4 rounded">{% trans 'Edit Profile' %}</a>
				{% elif profile.user.username in following %}
					<a href="#" class="bg-gray-300 text-gray-700 py-2 px-4 rounded"><span style="color:white;">{% trans 'Send Message' %}</span></a>
					<a href="#" class="bg-gray-300 text-gray-700 py-2 px-4 rounded"style="color:rgb(255, 255, 255);" onclick="follow();"><span style="color:white;">{% trans 'UnFollow' %}</span></a>
				{% else %}
					<button class="bg-gray-300 text-gray-700 py-2 px-4 rounded" onclick="follow();">{% trans 'Follow' %}</button> 
				{% endif %}
			 </span>
        </li>
      </ul>
    </div>
  </div>
  <div class="tabs" dir='rtl'>
	<ul class="flex border-b">
	<li class="-mb-px mr-1">
		<a class="bg-blue-800 inline-block py-2 px-4 font-semibold tab-btn" onclick="openTab(event, 'info')">‌{% trans 'Information' %}</a>
	  </li>
	  <li class="-mb-px mr-1">
		<a class="bg-blue-800 inline-block py-2 px-4 font-semibold tab-btn" onclick="openTab(event, 'translated')">‌{% trans 'Translated Animes' %}‌</a>
	  </li>
	  {% if profile.user == user %}
	  <li class="mr-1">
		<a class="bg-blue-800 inline-block py-2 px-4 font-semibold tab-btn" onclick="openTab(event, 'saved')">‌{% trans 'Favorite Animes' %}</a>
	  </li>
	  {% endif %}
	</ul>

	<!-- محتوای تب -->
	<div id="info" class="tbs p-4" >
	  <h3 class="text-xl font-bold">‌{% trans 'Information' %}</h3>
	  <ul class="mt-4 flex flex-col">
		{% if profile.admin %}
			<li class="py-2 border-b border-gray-200">
			<a href='tel:{{ info.phone }}' class="font-semibold">{% trans 'Phone Number' %}: {{ info.phone }}</a>
			</li>
			<li class="py-2 border-b border-gray-200">
			<a href='{{ info.telegram }}' class="font-semibold">{% trans 'Telegram ID' %}: {{ info.telegram }}</a>
			</li>
			{% if profile.manager %}
				<li class="py-2 border-b border-gray-200">
					<p class="font-semibold">{% trans 'Manager' %}</p>
				</li>
			{% else %}
			{% if profile.translator %}
				<li class="py-2 border-b border-gray-200">
					<p class="font-semibold">{% trans 'Translator' %}</p>
				</li>
			{% endif %}
			{% if profile.bloger %}
				<li class="py-2 border-b border-gray-200">
					<p class="font-semibold">{% trans 'Blogger' %}</p>
				</li>
			{% endif %}
			{% endif %}
		{% else %}
			<li class="py-2 border-b border-gray-200">
			<p>{% trans 'This user has no employee information' %}</p>
			</li>
		{% endif %}
	  </ul>
	</div>
	<div id="translated" class="tbs p-4 hidden mt-8">
	  <h3 class="text-xl font-bold">‌{% trans 'Translated Animes' %}</h3>
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 mt-4">
            {% for similar in anims %}
                <div class="flex flex-col bg-gray-800 rounded-lg shadow-md overflow-hidden">
				 <a href="{% url 'anime:view' anim_name=similar.name_Japanese %}" class="text-blue-500 mt-2">
                    <img class="h-56 w-full object-cover" src="{{ similar.photo.url }}" alt="{{ similar.name_english }}">
                    <div class="p-4">
                        <h4 class="font-semibold text-lg">{{ similar.name_english }}</h4>
                        <p>{% trans 'Seasons' %}: {{ similar.seasion }}</p>
                        <p>{% trans 'Episodes' %}: {{ similar.max_episod }}</p>
                       
                    </div>
					</a>
                </div>
            {% endfor %}
        </div>
    </div>
	{% if profile.user == user %}
		<div id="saved" class="tbs p-4 hidden">
		  <h3 class="text-xl font-bold">‌{% trans 'Favorite Animes' %}</h3>
		  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 mt-4">
				{% for similar in saves %}
					<div class="flex flex-col bg-gray-800 rounded-lg shadow-md overflow-hidden">
					 <a href="{% url 'anime:view' anim_name=similar.name_Japanese %}" class="text-blue-500 mt-2">
						<img class="h-56 w-full object-cover" src="{{ similar.photo.url }}" alt="{{ similar.name_english }}">
						<div class="p-4">
							<h4 class="font-semibold text-lg">{{ similar.name_english }}</h4>
							<p>{% trans 'Seasons' %}: {{ similar.seasion }}</p>
							<p>{% trans 'Episodes' %}: {{ similar.max_episod }}</p>
						   
						</div>
						</a>
					</div>
				{% endfor %}
			</div>
	</div>
	{% endif %}
	</div>
  </div>


  <script>
    function follow() {
    
    var page_url = window.location.href.split('/');
    user_username = page_url[page_url.length - 2];
    console.log('follow request sent @ /follow/')

    $.post("{% url 'accounts:follow' %}",{'username':user_username}, function(response){
        console.log(response.html);
        $('.follow-section').html(response.html)
    }).fail(function(xhr){
        console.log('Follow failed with '+xhr.status+' '+'/follow/');
    });
    
    return false;
};
function openTab(evt, tabName) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tbs");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.opacity = "0";
    tabcontent[i].classList.add('hidden');
  }
  document.getElementById(tabName).style.opacity = "1";
  document.getElementById(tabName).classList.remove('hidden');
}
  </script>

{% endblock %}